# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

trigger:
- dev

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '^10.10.0'
  displayName: 'Install Node.js'

- script: |
    yarn
  displayName: 'Install dependencies'

- script: |
    yarn build
  displayName: 'Build Nuxt'

- script: |
    yarn test -w=2
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml' 
  displayName: 'Publish test results to Azure Pipelines'
